// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: gateway.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameGatewayService_StreamPackets_FullMethodName    = "/gateway.GameGatewayService/StreamPackets"
	GameGatewayService_NotifyConnect_FullMethodName    = "/gateway.GameGatewayService/NotifyConnect"
	GameGatewayService_NotifyDisconnect_FullMethodName = "/gateway.GameGatewayService/NotifyDisconnect"
)

// GameGatewayServiceClient is the client API for GameGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GameGatewayService 用于 Gateway 和 GameServer 之间的通信
type GameGatewayServiceClient interface {
	// StreamPackets 建立一个双向流，用于在 Gateway 和 GameServer 之间转发数据包
	StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GamePacket, GamePacket], error)
	// NotifyConnect 当客户端连接到 Gateway 时通知 GameServer
	// Gateway 会在客户端建立连接后立即调用此方法，携带连接元数据
	NotifyConnect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	// NotifyDisconnect 当客户端从 Gateway 断开时通知 GameServer
	// Gateway 会在客户端断开连接后调用此方法，以便 GameServer 清理资源
	NotifyDisconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
}

type gameGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameGatewayServiceClient(cc grpc.ClientConnInterface) GameGatewayServiceClient {
	return &gameGatewayServiceClient{cc}
}

func (c *gameGatewayServiceClient) StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GamePacket, GamePacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameGatewayService_ServiceDesc.Streams[0], GameGatewayService_StreamPackets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GamePacket, GamePacket]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameGatewayService_StreamPacketsClient = grpc.BidiStreamingClient[GamePacket, GamePacket]

func (c *gameGatewayServiceClient) NotifyConnect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, GameGatewayService_NotifyConnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameGatewayServiceClient) NotifyDisconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, GameGatewayService_NotifyDisconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameGatewayServiceServer is the server API for GameGatewayService service.
// All implementations must embed UnimplementedGameGatewayServiceServer
// for forward compatibility.
//
// GameGatewayService 用于 Gateway 和 GameServer 之间的通信
type GameGatewayServiceServer interface {
	// StreamPackets 建立一个双向流，用于在 Gateway 和 GameServer 之间转发数据包
	StreamPackets(grpc.BidiStreamingServer[GamePacket, GamePacket]) error
	// NotifyConnect 当客户端连接到 Gateway 时通知 GameServer
	// Gateway 会在客户端建立连接后立即调用此方法，携带连接元数据
	NotifyConnect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	// NotifyDisconnect 当客户端从 Gateway 断开时通知 GameServer
	// Gateway 会在客户端断开连接后调用此方法，以便 GameServer 清理资源
	NotifyDisconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	mustEmbedUnimplementedGameGatewayServiceServer()
}

// UnimplementedGameGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameGatewayServiceServer struct{}

func (UnimplementedGameGatewayServiceServer) StreamPackets(grpc.BidiStreamingServer[GamePacket, GamePacket]) error {
	return status.Error(codes.Unimplemented, "method StreamPackets not implemented")
}
func (UnimplementedGameGatewayServiceServer) NotifyConnect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyConnect not implemented")
}
func (UnimplementedGameGatewayServiceServer) NotifyDisconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyDisconnect not implemented")
}
func (UnimplementedGameGatewayServiceServer) mustEmbedUnimplementedGameGatewayServiceServer() {}
func (UnimplementedGameGatewayServiceServer) testEmbeddedByValue()                            {}

// UnsafeGameGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameGatewayServiceServer will
// result in compilation errors.
type UnsafeGameGatewayServiceServer interface {
	mustEmbedUnimplementedGameGatewayServiceServer()
}

func RegisterGameGatewayServiceServer(s grpc.ServiceRegistrar, srv GameGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGameGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameGatewayService_ServiceDesc, srv)
}

func _GameGatewayService_StreamPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameGatewayServiceServer).StreamPackets(&grpc.GenericServerStream[GamePacket, GamePacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameGatewayService_StreamPacketsServer = grpc.BidiStreamingServer[GamePacket, GamePacket]

func _GameGatewayService_NotifyConnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameGatewayServiceServer).NotifyConnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameGatewayService_NotifyConnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameGatewayServiceServer).NotifyConnect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameGatewayService_NotifyDisconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameGatewayServiceServer).NotifyDisconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameGatewayService_NotifyDisconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameGatewayServiceServer).NotifyDisconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameGatewayService_ServiceDesc is the grpc.ServiceDesc for GameGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.GameGatewayService",
	HandlerType: (*GameGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyConnect",
			Handler:    _GameGatewayService_NotifyConnect_Handler,
		},
		{
			MethodName: "NotifyDisconnect",
			Handler:    _GameGatewayService_NotifyDisconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPackets",
			Handler:       _GameGatewayService_StreamPackets_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gateway.proto",
}
