// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GamePacket is a generic packet envelope for Gateway and GameServer communication
type GamePacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SessionID uniquely identifies a client connection on Gateway side
	SessionId int64 `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// MsgID is the original message ID (corresponds to Protobuf message type)
	// For normal game messages, this is the actual message ID
	// For connection lifecycle events, this field is ignored (use metadata instead)
	MsgId int32 `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	// Payload contains the original message body binary data (passthrough, no re-serialization)
	// Empty for connection/disconnection events
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Metadata is used for extended fields like TraceContext and packet type
	// For connection events, metadata must contain:
	//   - "packet_type": "connect" or "disconnect"
	//   - For "connect": "client_ip", "protocol", "connect_time" (Unix milliseconds)
	//     Note: gateway_name is obtained from gRPC header during stream establishment, not from packet metadata
	//   - For "disconnect": "reason", "disconnect_time" (Unix milliseconds)
	//
	// For normal game messages, metadata may contain:
	//   - "trace_id": OpenTelemetry trace ID
	//   - "span_id": OpenTelemetry span ID
	Metadata map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// For broadcast: if this field has values, session_id is ignored and message is broadcast to all listed sessions
	TargetSessionIds []int64 `protobuf:"varint,5,rep,packed,name=target_session_ids,json=targetSessionIds,proto3" json:"target_session_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GamePacket) Reset() {
	*x = GamePacket{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePacket) ProtoMessage() {}

func (x *GamePacket) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePacket.ProtoReflect.Descriptor instead.
func (*GamePacket) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GamePacket) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *GamePacket) GetMsgId() int32 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GamePacket) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GamePacket) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GamePacket) GetTargetSessionIds() []int64 {
	if x != nil {
		return x.TargetSessionIds
	}
	return nil
}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\agateway\"\x86\x02\n" +
	"\n" +
	"GamePacket\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x03R\tsessionId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\x05R\x05msgId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12=\n" +
	"\bmetadata\x18\x04 \x03(\v2!.gateway.GamePacket.MetadataEntryR\bmetadata\x12,\n" +
	"\x12target_session_ids\x18\x05 \x03(\x03R\x10targetSessionIds\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012S\n" +
	"\x12GameGatewayService\x12=\n" +
	"\rStreamPackets\x12\x13.gateway.GamePacket\x1a\x13.gateway.GamePacket(\x010\x01BGZ.github.com/SkynetNext/game-gateway/api;gateway\xaa\x02\x14Game.Networking.Grpcb\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gateway_proto_goTypes = []any{
	(*GamePacket)(nil), // 0: gateway.GamePacket
	nil,                // 1: gateway.GamePacket.MetadataEntry
}
var file_gateway_proto_depIdxs = []int32{
	1, // 0: gateway.GamePacket.metadata:type_name -> gateway.GamePacket.MetadataEntry
	0, // 1: gateway.GameGatewayService.StreamPackets:input_type -> gateway.GamePacket
	0, // 2: gateway.GameGatewayService.StreamPackets:output_type -> gateway.GamePacket
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
