// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: gateway.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameGatewayService_StreamPackets_FullMethodName = "/gateway.GameGatewayService/StreamPackets"
)

// GameGatewayServiceClient is the client API for GameGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GameGatewayService handles communication between Gateway and GameServer
type GameGatewayServiceClient interface {
	// StreamPackets establishes a bidirectional stream for forwarding packets between Gateway and GameServer
	// Connection lifecycle events (connect/disconnect) are sent as GamePacket with metadata["packet_type"]
	StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GamePacket, GamePacket], error)
}

type gameGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameGatewayServiceClient(cc grpc.ClientConnInterface) GameGatewayServiceClient {
	return &gameGatewayServiceClient{cc}
}

func (c *gameGatewayServiceClient) StreamPackets(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GamePacket, GamePacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GameGatewayService_ServiceDesc.Streams[0], GameGatewayService_StreamPackets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GamePacket, GamePacket]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameGatewayService_StreamPacketsClient = grpc.BidiStreamingClient[GamePacket, GamePacket]

// GameGatewayServiceServer is the server API for GameGatewayService service.
// All implementations must embed UnimplementedGameGatewayServiceServer
// for forward compatibility.
//
// GameGatewayService handles communication between Gateway and GameServer
type GameGatewayServiceServer interface {
	// StreamPackets establishes a bidirectional stream for forwarding packets between Gateway and GameServer
	// Connection lifecycle events (connect/disconnect) are sent as GamePacket with metadata["packet_type"]
	StreamPackets(grpc.BidiStreamingServer[GamePacket, GamePacket]) error
	mustEmbedUnimplementedGameGatewayServiceServer()
}

// UnimplementedGameGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameGatewayServiceServer struct{}

func (UnimplementedGameGatewayServiceServer) StreamPackets(grpc.BidiStreamingServer[GamePacket, GamePacket]) error {
	return status.Error(codes.Unimplemented, "method StreamPackets not implemented")
}
func (UnimplementedGameGatewayServiceServer) mustEmbedUnimplementedGameGatewayServiceServer() {}
func (UnimplementedGameGatewayServiceServer) testEmbeddedByValue()                            {}

// UnsafeGameGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameGatewayServiceServer will
// result in compilation errors.
type UnsafeGameGatewayServiceServer interface {
	mustEmbedUnimplementedGameGatewayServiceServer()
}

func RegisterGameGatewayServiceServer(s grpc.ServiceRegistrar, srv GameGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGameGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameGatewayService_ServiceDesc, srv)
}

func _GameGatewayService_StreamPackets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameGatewayServiceServer).StreamPackets(&grpc.GenericServerStream[GamePacket, GamePacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GameGatewayService_StreamPacketsServer = grpc.BidiStreamingServer[GamePacket, GamePacket]

// GameGatewayService_ServiceDesc is the grpc.ServiceDesc for GameGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.GameGatewayService",
	HandlerType: (*GameGatewayServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamPackets",
			Handler:       _GameGatewayService_StreamPackets_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gateway.proto",
}
